# Generated by Django 6.0.5 on 2026-05-16 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from ..models import cover_path
from ..fields import XhtmlField, SmilField


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploader', models.CharField(max_length=50)),
                ('basename', models.SlugField(allow_unicode=True, default='')),
                ('identifier', models.CharField(help_text='Analogous to dc:identifier in the OPF file', max_length=100)),
                ('title', models.CharField(help_text='Analogous to dc:title in the OPF file', max_length=100)),
                ('language', models.CharField(help_text='Analogous to dc:language in the OPF file', max_length=100)),
                ('is_public', models.BooleanField(default=False)),
                ('rootfile_path', models.CharField(max_length=100)),
                ('cover', models.ImageField(blank=True, upload_to=cover_path)),
            ],
        ),
        migrations.CreateModel(
            name='Epubcheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epubcheck', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epubeditor.book')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('UL', 'Uploader'), ('ED', 'Editor'), ('RD', 'Reader')], max_length=2)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epubeditor.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='users',
            field=models.ManyToManyField(through='epubeditor.Role', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FileLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
                ('locked', models.BooleanField(null=True)),
                ('timestamp', models.DateTimeField(null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epubeditor.book')),
            ],
            options={
                'unique_together': {('book', 'path')},
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100)),
                ('trigger', models.CharField(choices=[('I', 'Init'), ('N', 'Normal'), ('U', 'Undo'), ('R', 'Redo')], max_length=1)),
                ('type', models.CharField(choices=[('C', 'Create'), ('U', 'Update'), ('D', 'Delete'), ('M', 'Merge'), ('S', 'Split')], max_length=1)),
                ('old', models.JSONField(null=True)),
                ('new', models.JSONField(null=True)),
                ('old_xhtml', XhtmlField(null=True)),
                ('new_xhtml', XhtmlField(null=True)),
                ('old_smil', SmilField(null=True)),
                ('new_smil', SmilField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epubeditor.book')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['book', 'item_id'], name='epubeditor__book_id_22c8a3_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('uploader', 'basename')},
        ),
    ]
